version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: 87787112-d045-4e13-8ffe-f97b0b208a52
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage,-Dmp.jwt.token.header=Authorization"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  #mounts:
  #  - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
  #    value: |
  #      <server>
  #         <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
  #      </server>
